INSERT INTO users (login, password, role) VALUES ('Admin', 'qwerty', 'Administrator');

INSERT INTO restaurants (name, description, address) VALUES 
('Restaurant 1', 'Here is description', 'City, Street and Numer'),
('Restaurant 2', 'Here is description', 'City, Street and Numer'),
('Restaurant 3', 'Here is description', 'City, Street and Numer'),
('Restaurant 4', 'Here is description', 'City, Street and Numer'),
('Restaurant 5', 'Here is description', 'City, Street and Numer'),
('Restaurant 6', 'Here is description', 'City, Street and Numer'),
('Restaurant 7', 'Here is description', 'City, Street and Numer'),
('Restaurant 8', 'Here is description', 'City, Street and Numer'),
('Restaurant 9', 'Here is description', 'City, Street and Numer'),
('Restaurant 10', 'Here is description', 'City, Street and Numer'),
('Restaurant 11', 'Here is description', 'City, Street and Numer'),
('Restaurant 22', 'Here is description', 'City, Street and Numer'),
('Restaurant 33', 'Here is description', 'City, Street and Numer'),
('Restaurant 44', 'Here is description', 'City, Street and Numer'),
('Restaurant 55', 'Here is description', 'City, Street and Numer'),
('Restaurant 66', 'Here is description', 'City, Street and Numer'),
('Restaurant 77', 'Here is description', 'City, Street and Numer'),
('Restaurant 88', 'Here is description', 'City, Street and Numer'),
('Restaurant 99', 'Here is description', 'City, Street and Numer'),
('Restaurant 100', 'Here is description', 'City, Street and Numer'),
